### ISSUE TITLE
Errore

### ISSUE THREAD

**Issue by iannellog** [ValerioMontanaro/Prog_Programmazione_2324#11]
Ho eseguito l'applicazione con il comnando
> `python main.py`

ho fornito i seguenti valori:
> vicini nel KNN : 5
> dimensione del test set (ad esempio, 20%): 25
> metrica desiderata (un numero intero compreso tra 1 e 6): 6

Il programma solleva un'eccezione:

    Traceback (most recent call last):
      File "C:\Users\ianne\Home\Didattica\Programmazione\2023-2024\Progetti\Montanaro-Di_Cicco-Gallo\Prog_Programmazione_2324\main.py", line 105, in <module>
        metrics_visualizer = MetricsVisualizer(method_input, risultati, scelta_int)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\ianne\Home\Didattica\Programmazione\2023-2024\Progetti\Montanaro-Di_Cicco-Gallo\Prog_Programmazione_2324\metricsVisualizer.py", line 54, in __init__
    self.save_to_excel( results[0], scelta, df2)
      File "C:\Users\ianne\Home\Didattica\Programmazione\2023-2024\Progetti\Montanaro-Di_Cicco-Gallo\Prog_Programmazione_2324\metricsVisualizer.py", line 116, in save_to_excel
        'Value': list(metrics_result)
                      ^^^^^^^^^^^^^^
    NameError: name 'metrics_result' is not defined`

**Comment by iannellog** [comment]
Ho verificato che l'errore compare se si scegli l'holdout, mnadre funziona se si sceglie Stratified Cross Validation

**Comment by CarloDiCicco** [comment]
Bug corretto nel commit del 5/02/2024 (revision number: 4d01780eeeae053316e720e6f3550bee32b8afd2).
